version: 2

before:
  hooks:
    - go mod tidy
    # - go generate ./...

builds:
  - main: ./src/main.go
    env:
      - CGO_ENABLED=0
    goos: [linux, windows]
    goarch: [amd64]
    ldflags: -s -w -X main.version={{.Version}}

archives:
  # - formats: [tar.gz]
  - formats: ["binary"]
    name_template: >-
      {{ .ProjectName }}-
      {{- title .Os }}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

    # format_overrides:
    #   - goos: windows
    #     formats: [zip]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
